database:
  host: localhost
  port: 3307
  user: root
  password: 1234
  name: hackathon2025
  sslmode: disable
  max_connections: 100

server:
  port: 8080
  host: 0.0.0.0
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  allow_origins:
    - "*"

mqtt:
  host: 10.4.41.187
  port: 1883
  username: test
  password: 1234
  client_id: go-mqtt-subscriber
