version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app   # Mount the server directory to the container for live-reloading
    networks:
      - app-network
    environment:
      - SERVER_PORT=8080
    depends_on:
      - client

networks:
  app-network:
    driver: bridge
