version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goapp-mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hackathon2025
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goapp_network
    restart: unless-stopped

  app:
    build: .
    container_name: goapp-server
    ports:
      - "8080:8080"
    environment:
      HACKATHON_2025_DATABASE_HOST: goapp-mysql
      HACKATHON_2025_DATABASE_PORT: 3306
      HACKATHON_2025_DATABASE_USER: root
      HACKATHON_2025_DATABASE_PASSWORD: 1234
      HACKATHON_2025_DATABASE_NAME: hackathon2025
    depends_on:
      - mysql
    networks:
      - goapp_network
    restart: unless-stopped

networks:
  goapp_network:
    driver: bridge

volumes:
  mysql_data: