version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goapp-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hackathon2025
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - goapp_network
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp-server
    ports:
      - "3001:8080"
    environment:
      HACKATHON_2025_DATABASE_HOST: goapp-mysql  # Use container name
      HACKATHON_2025_DATABASE_PORT: 3306
      HACKATHON_2025_DATABASE_USER: root
      HACKATHON_2025_DATABASE_PASSWORD: 1234
      HACKATHON_2025_DATABASE_NAME: hackathon2025
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goapp_network
    command: sh -c "make db-start && air" # Ensure make command runs before starting app

networks:
  goapp_network:
    driver: bridge

volumes:
  mysql_data:
