services:
  mysql:
    image: mysql:8.0
    container_name: goapp-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hackathon2025
      # Remove MYSQL_USER and MYSQL_PASSWORD for root
      # Or create a different user if needed:
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goapp_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp-server
    ports:
      - "3001:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root           # This is fine because it's for connecting
      DB_PASSWORD: 1234       # Uses MYSQL_ROOT_PASSWORD value
      DB_NAME: hackathon2025
    depends_on:
      - mysql
    networks:
      - goapp_network

volumes:
  mysql_data:

networks:
  goapp_network: