services:
  mysql:
    image: mysql:8.0
    container_name: goapp-mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"  # You can keep this as is or change based on your VM's requirements
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Rsv18221}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hackathon2025}
      MYSQL_ROOT_HOST: '%'
      TZ: UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-Rsv18221}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goapp_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp-server
    ports:
      - "8080:8080"  # Changed to expose on standard port 8080
    environment:
      HACKATHON_2025_DATABASE_HOST: ${DB_HOST:-goapp-mysql}
      HACKATHON_2025_DATABASE_PORT: ${DB_PORT:-3306}
      HACKATHON_2025_DATABASE_USER: ${DB_USER:-root}
      HACKATHON_2025_DATABASE_PASSWORD: ${DB_PASSWORD:-Rsv18221}
      HACKATHON_2025_DATABASE_NAME: ${DB_NAME:-hackathon2025}
      HACKATHON_2025_DATABASE_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-100}
      HACKATHON_2025_SERVER_HOST: "0.0.0.0"  # Important for VM deployment
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goapp_network
    restart: unless-stopped

networks:
  goapp_network:
    driver: bridge

volumes:
  mysql_data: