USE hackathon2025;
SELECT 
    CONCAT('ALTER TABLE ', TABLE_NAME, ' DROP FOREIGN KEY ', CONSTRAINT_NAME, ';') AS drop_command
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE 
    TABLE_SCHEMA = 'hackathon2025'
    AND REFERENCED_TABLE_NAME IS NOT NULL;


DROP TABLE IF EXISTS parking_warning;
DROP TABLE IF EXISTS toilets;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS buildings;

DROP DATABASE IF EXISTS hackathon2025;
