USE hackathon2025;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS booking_time_periods;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS buildings;

SET FOREIGN_KEY_CHECKS = 1;

DROP DATABASE IF EXISTS hackathon2025;